"""Dependency wiring for command families used by the CLI."""


def configure_runtime(
    *,
    configure_docs,
    configure_launch,
    configure_progress,
    configure_closeout,
    configure_merge,
    configure_review_unit,
    dependencies,
):
    configure_docs(
        atomic_write_text=dependencies["atomic_write_text"],
        parse_dependency_list=dependencies["parse_dependency_list"],
        parse_release_stages=dependencies["parse_release_stages"],
        parse_consequence_triggers=dependencies["parse_consequence_triggers"],
        legacy_hashes=dependencies["legacy_hashes"],
    )
    configure_launch(
        run_prd_controller_fn=dependencies["run_prd_controller"],
        print_payload_fn=dependencies["print_payload"],
        completion_projection_for_run_fn=dependencies[
            "completion_projection_for_run"
        ],
        safely_ensure_progress_supervisor_fn=dependencies[
            "safely_ensure_progress_supervisor"
        ],
        safely_progress_dashboard_status_fn=dependencies[
            "safely_progress_dashboard_status"
        ],
        gauntlet_cli_path_fn=dependencies["gauntlet_cli_path"],
    )
    configure_progress(
        load_launch_set=dependencies["load_launch_set"],
        launch_projections=dependencies["launch_projections"],
        run_prd_controller=dependencies["run_prd_controller"],
        print_payload=dependencies["print_payload"],
    )
    configure_closeout(
        gap_review_text=dependencies["gap_review_text"],
        run_authority_granted=dependencies["run_authority_granted"],
        run_prd_controller=dependencies["run_prd_controller"],
        print_payload=dependencies["print_payload"],
    )
    configure_merge(
        load_launch_set=dependencies["load_launch_set"],
        launch_source_text=dependencies["launch_source_text"],
        prd_controller_path=dependencies["prd_controller_path"],
        run_authority_granted=dependencies["run_authority_granted"],
        run_prd_controller=dependencies["run_prd_controller"],
        print_payload=dependencies["print_payload"],
    )
    configure_review_unit(
        merge_input_path=dependencies["merge_input_path"],
        run_prd_controller=dependencies["run_prd_controller"],
        branch_name=dependencies["branch_name"],
        current_head=dependencies["current_head"],
        dirty_paths=dependencies["dirty_paths"],
        checks_state=dependencies["checks_state"],
        delete_remote_branch=dependencies["delete_remote_branch"],
        print_payload=dependencies["print_payload"],
    )
